name: marp-to-pages
concurrency: marp-to-pages

on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Marp Build
        uses: docker://marpteam/marp-cli:v4.1.1
        with:
          args: '*.slides.md --pdf --allow-local-files'
        env:
          MARP_USER: root:root

      - name: Move files to dist dir
        run: mkdir -p dist && mv *.slides.pdf dist/

      - name: Deploy preview
        if: ${{ github.event_name == 'pull_request' }}
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist/
          preview-branch: gh-pages
          umbrella-dir: pr-preview

      - name: Deploy production
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./dist/
          clean-exclude: pr-preview/
